# Generated by Django 6.0.1 on 2026-01-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('duration', models.DurationField()),
                ('poster', models.ImageField(upload_to='movie_posters/')),
                ('release_date', models.DateField()),
                ('genre', models.ManyToManyField(related_name='movies', to='base.genre')),
                ('language', models.ManyToManyField(related_name='movies', to='base.language')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
