# Generated by Django 6.0.1 on 2026-01-28 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('slots', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='end_time',
        ),
        migrations.AddField(
            model_name='slot',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='base.language'),
            preserve_default=False,
        ),
    ]
