# Generated by Django 6.0.1 on 2026-01-23 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=300)),
                ('rows', models.PositiveIntegerField()),
                ('seats_per_rows', models.PositiveIntegerField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cinemas', to='base.city')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'location', 'city'), name='unique_cinema_per_location_city')],
            },
        ),
    ]
