# Generated by Django 6.0.1 on 2026-01-28 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cinema',
            old_name='seats_per_rows',
            new_name='seats_per_row',
        ),
    ]
