# Generated by Django 6.0.1 on 2026-01-29 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0002_rename_seats_per_rows_cinema_seats_per_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
