# Generated by Django 6.0.1 on 2026-01-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.IntegerField(choices=[(0, 'Cancelled'), (1, 'Booked'), (2, 'Pending')], default=2),
        ),
    ]
